Repository nbcamp-pjs/Tming-BE, pull requests merged in 2024-01, with the labels that each got.

#4 restdocs 배포 추가
  .github/workflows/gradle.yml
Labels: docs

#11 [Feat] 이메일 인증용 의존성 추가
  build.gradle
Labels: feat

#7 feat: JwtUtil 추가
  build.gradle
  src/main/java/com/spring/tming/global/jwt/JwtUtil.java
  src/main/resources/application.yml
Labels: feat

#21 s3 config 추가
  build.gradle
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/s3/S3Config.java
  src/main/java/com/spring/tming/global/s3/S3Provider.java
  src/main/java/com/spring/tming/global/validator/S3Validator.java
  src/main/resources/application.yml
Labels: feat

#22 s3 provider 테스트코드 추가
  src/main/resources/images/sparta.png
  src/test/java/com/spring/tming/global/s3/S3ProviderTest.java
Labels: test

#26 [Feat] email인증을 위한 configuration 추가
  src/main/java/com/spring/tming/domain/emailVerify/config/EmailConfig.java
Labels: feat

#29 email config 수정
  src/main/java/com/spring/tming/domain/emailVerify/config/EmailConfig.java
  src/main/java/com/spring/tming/global/mail/EmailConfig.java
  src/main/resources/application.yml
Labels: fix

#33 [Feat] ResultCode에 에러메시지 추가 및 이메일 유효성 검사 추가
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/EmailCheckValidator.java
Labels: feat

#30 로그인 기능 구현
  .gitignore
  src/main/java/com/spring/tming/domain/user/dto/request/LoginReq.java
  src/main/java/com/spring/tming/domain/user/entity/User.java
  src/main/java/com/spring/tming/domain/user/repository/UserRepository.java
  src/main/java/com/spring/tming/global/jwt/JwtUtil.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/redis/RedisConfig.java
  src/main/java/com/spring/tming/global/redis/RedisUtil.java
  src/main/java/com/spring/tming/global/security/JwtAuthenticationFilter.java
  src/main/java/com/spring/tming/global/security/JwtAuthorizationFilter.java
  src/main/java/com/spring/tming/global/security/SecurityConfig.java
  src/main/java/com/spring/tming/global/security/UserDetailsImpl.java
  src/main/java/com/spring/tming/global/security/UserDetailsServiceImpl.java
  src/main/java/com/spring/tming/global/validator/EmailCheckValidator.java
  src/main/java/com/spring/tming/global/validator/UserValidator.java
  src/main/resources/application.yml
Labels: feat, refactor

#40 댓글 저장 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/comment/controller/CommentController.java
  src/main/java/com/spring/tming/domain/comment/dto/request/CommentSaveReq.java
  src/main/java/com/spring/tming/domain/comment/dto/response/CommentSaveRes.java
  src/main/java/com/spring/tming/domain/comment/entity/Comment.java
  src/main/java/com/spring/tming/domain/comment/repository/CommentRepository.java
  src/main/java/com/spring/tming/domain/comment/service/CommentService.java
  src/main/java/com/spring/tming/domain/comment/service/CommentServiceMapper.java
  src/main/java/com/spring/tming/global/security/SecurityConfig.java
  src/test/java/com/spring/tming/domain/BaseMvcTest.java
  src/test/java/com/spring/tming/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/spring/tming/global/security/MockSpringSecurityFilter.java
  src/test/java/com/spring/tming/test/UserTest.java
Labels: docs, feat

#43 댓글 수정 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/comment/controller/CommentController.java
  src/main/java/com/spring/tming/domain/comment/dto/request/CommentUpdateReq.java
  src/main/java/com/spring/tming/domain/comment/dto/response/CommentUpdateRes.java
  src/main/java/com/spring/tming/domain/comment/repository/CommentRepository.java
  src/main/java/com/spring/tming/domain/comment/service/CommentService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/CommentValidator.java
  src/test/java/com/spring/tming/domain/comment/controller/CommentControllerTest.java
Labels: docs, feat

#46 댓글 삭제 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/comment/controller/CommentController.java
  src/main/java/com/spring/tming/domain/comment/dto/request/CommentDeleteReq.java
  src/main/java/com/spring/tming/domain/comment/dto/response/CommentDeleteRes.java
  src/main/java/com/spring/tming/domain/comment/service/CommentService.java
  src/test/java/com/spring/tming/domain/comment/controller/CommentControllerTest.java
Labels: docs, feat

#47 댓글 전체 조회 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/comment/controller/CommentController.java
  src/main/java/com/spring/tming/domain/comment/dto/response/CommentGetRes.java
  src/main/java/com/spring/tming/domain/comment/dto/response/CommentGetResList.java
  src/main/java/com/spring/tming/domain/comment/repository/CommentRepository.java
  src/main/java/com/spring/tming/domain/comment/service/CommentService.java
  src/main/java/com/spring/tming/domain/comment/service/CommentServiceMapper.java
  src/test/java/com/spring/tming/domain/comment/controller/CommentControllerTest.java
Labels: docs, feat

#51 모집글 좋아요 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/post/controller/PostController.java
  src/main/java/com/spring/tming/domain/post/dto/request/PostLikeReq.java
  src/main/java/com/spring/tming/domain/post/dto/response/PostLikeRes.java
  src/main/java/com/spring/tming/domain/post/entity/PostLike.java
  src/main/java/com/spring/tming/domain/post/entity/PostLikeId.java
  src/main/java/com/spring/tming/domain/post/repository/PostLikeRepository.java
  src/main/java/com/spring/tming/domain/post/service/PostLikeService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/PostValidator.java
  src/test/java/com/spring/tming/domain/post/controller/PostControllerTest.java
Labels: docs, feat

#41 feat: 회원가입 구현
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/dto/request/SignupReq.java
  src/main/java/com/spring/tming/domain/user/dto/response/SignupRes.java
  src/main/java/com/spring/tming/domain/user/entity/User.java
  src/main/java/com/spring/tming/domain/user/repository/UserRepository.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
  src/main/java/com/spring/tming/global/entity/Role.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/EmailCheckValidator.java
  src/main/java/com/spring/tming/global/validator/UserValidator.java
  src/test/java/com/spring/tming/test/UserTest.java
Labels: feat, refactor

#37 [Feat] 이메일 인증 서비스 전반 및 redis 도입
  src/main/java/com/spring/tming/domain/emailVerify/controller/EmailController.java
  src/main/java/com/spring/tming/domain/emailVerify/dto/request/EmailCheckReq.java
  src/main/java/com/spring/tming/domain/emailVerify/dto/request/EmailReq.java
  src/main/java/com/spring/tming/domain/emailVerify/dto/response/EmailRes.java
  src/main/java/com/spring/tming/domain/emailVerify/service/EmailSendService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/EmailCheckValidator.java
Labels: feat, refactor

#57 refactor: username,password validate 구현
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/UserValidator.java
Labels: refactor

#52 모집글 좋아요 취소 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/post/controller/PostController.java
  src/main/java/com/spring/tming/domain/post/dto/request/PostUnlikeReq.java
  src/main/java/com/spring/tming/domain/post/dto/response/PostUnlikeRes.java
  src/main/java/com/spring/tming/domain/post/service/PostLikeService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/PostValidator.java
  src/test/java/com/spring/tming/domain/post/controller/PostControllerTest.java
Labels: docs, feat

#62 filter 버그 수정
  src/main/java/com/spring/tming/domain/comment/entity/Comment.java
  src/main/java/com/spring/tming/domain/user/repository/UserRepository.java
  src/main/java/com/spring/tming/global/jwt/JwtUtil.java
  src/main/java/com/spring/tming/global/redis/RedisConfig.java
  src/main/java/com/spring/tming/global/security/JwtAuthorizationFilter.java
Labels: bug

#63 실행 시 서버 timezone 변경
  infra/Dockerfile
Labels: fix

#64 유저 프로필 조회 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/dto/response/UserGetRes.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
  src/test/java/com/spring/tming/domain/user/controller/UserControllerTest.java
Labels: docs, feat

#68 유저 팔로우 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/dto/request/FollowReq.java
  src/main/java/com/spring/tming/domain/user/dto/response/FollowRes.java
  src/main/java/com/spring/tming/domain/user/entity/Follow.java
  src/main/java/com/spring/tming/domain/user/entity/FollowId.java
  src/main/java/com/spring/tming/domain/user/repository/FollowRepository.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/UserValidator.java
  src/test/java/com/spring/tming/domain/user/controller/UserControllerTest.java
Labels: docs, feat

#71 유저 팔로우 취소 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/dto/request/UnfollowReq.java
  src/main/java/com/spring/tming/domain/user/dto/response/UnfollowRes.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/UserValidator.java
  src/test/java/com/spring/tming/domain/user/controller/UserControllerTest.java
Labels: docs, feat

#72 모집글 좋아요 취소 api method 변경
  src/main/java/com/spring/tming/domain/post/controller/PostController.java
  src/test/java/com/spring/tming/domain/post/controller/PostControllerTest.java
Labels: fix

#76 유저 팔로워 목록 조회 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/dto/response/FollowerGetRes.java
  src/main/java/com/spring/tming/domain/user/dto/response/FollowerGetResList.java
  src/main/java/com/spring/tming/domain/user/repository/UserRepository.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
  src/test/java/com/spring/tming/domain/user/controller/UserControllerTest.java
Labels: docs, feat

#77 유저 팔로잉 목록 조회 api 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/dto/response/FollowingGetRes.java
  src/main/java/com/spring/tming/domain/user/dto/response/FollowingGetResList.java
  src/main/java/com/spring/tming/domain/user/entity/User.java
  src/main/java/com/spring/tming/domain/user/repository/UserRepository.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
  src/test/java/com/spring/tming/domain/user/controller/UserControllerTest.java
Labels: docs, feat

#78 request headers 수정
  src/test/java/com/spring/tming/domain/BaseMvcTest.java
Labels: fix

#66 feat: 로그인시 userId 반환
  src/main/java/com/spring/tming/domain/user/dto/response/LoginRes.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
  src/main/java/com/spring/tming/global/jwt/JwtUtil.java
  src/main/java/com/spring/tming/global/redis/RedisUtil.java
  src/main/java/com/spring/tming/global/security/JwtAuthenticationFilter.java
  src/main/java/com/spring/tming/global/security/JwtAuthorizationFilter.java
  src/main/java/com/spring/tming/global/validator/UserValidator.java
Labels: feat, refactor

#80 유저 프로필 조회 시 팔로워/팔로잉 수 추가
  src/main/java/com/spring/tming/domain/user/entity/Follow.java
  src/main/java/com/spring/tming/domain/user/repository/UserRepository.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
Labels: fix

#86 Fix: login path
  src/main/java/com/spring/tming/global/security/SecurityConfig.java
Labels: fix

#59 이메일 인증 API 추가
  src/main/java/com/spring/tming/domain/emailVerify/controller/EmailController.java
  src/main/java/com/spring/tming/domain/emailVerify/dto/response/EmailAuthRes.java
  src/main/java/com/spring/tming/domain/emailVerify/service/EmailSendService.java
Labels: feat

#98 [FEAT][FIX] 브랜치 최신화 및 클래스 수정
  src/main/java/com/spring/tming/domain/applicant/Applicant.java
  src/main/java/com/spring/tming/domain/applicant/ApplicantId.java
Labels: feat, fix

#100 refactor: redis에서 userId 가져오는거 변환방식 수정
  src/main/java/com/spring/tming/global/security/JwtAuthorizationFilter.java
Labels: refactor

#102 모집글 신청 Dto 생성
  src/main/java/com/spring/tming/domain/applicant/dto/request/ApplicantSaveReq.java
  src/main/java/com/spring/tming/domain/applicant/dto/response/ApplicantSaveRes.java
  src/main/java/com/spring/tming/domain/applicant/entity/Applicant.java
  src/main/java/com/spring/tming/domain/applicant/entity/ApplicantId.java
Labels: feat

#106 [REFACTOR] 모집신청서비스 entity 변수명 통일
  src/main/java/com/spring/tming/domain/applicant/entity/ApplicantId.java
Labels: refactor

#110 이미 팔로우한 유저인지 확인로직 추가
  src/main/java/com/spring/tming/domain/user/dto/response/UserGetRes.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
Labels: fix

#113 프로필 조회 시 followed를 못가져오는 버그 수정
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/entity/Follow.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/domain/user/service/UserServiceMapper.java
  src/test/java/com/spring/tming/domain/user/controller/UserControllerTest.java
Labels: bug

#116 Feat: 로그아웃 기능 구현 수정하기
  build.gradle
  src/main/java/com/spring/tming/domain/user/controller/UserController.java
  src/main/java/com/spring/tming/domain/user/service/UserService.java
  src/main/java/com/spring/tming/global/jwt/JwtUtil.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/redis/RedisConfig.java
  src/main/java/com/spring/tming/global/security/ExceptionHandlerFilter.java
  src/main/java/com/spring/tming/global/security/LogoutHandlerImpl.java
  src/main/java/com/spring/tming/global/security/LogoutSuccessHandlerImpl.java
  src/main/java/com/spring/tming/global/security/SecurityConfig.java
  src/main/java/com/spring/tming/global/validator/TokenValidator.java
Labels: feat, refactor

#118 단건조회시 조회수 올리기
  src/main/java/com/spring/tming/domain/post/controller/PostController.java
  src/main/java/com/spring/tming/domain/post/entity/Post.java
  src/main/java/com/spring/tming/domain/post/service/PostService.java
  src/main/java/com/spring/tming/global/redis/RedisUtil.java
Labels: feat

#123 [FEAT] 팀원 신청 및 승인에 관한 Entity 및 컨트롤러, 서비스, Dto, Id 등 패키지 추가
  src/main/java/com/spring/tming/domain/members/controller/MemberController.java
  src/main/java/com/spring/tming/domain/members/dto/request/MemberAdmitReq.java
  src/main/java/com/spring/tming/domain/members/dto/response/MemberAdmitRes.java
  src/main/java/com/spring/tming/domain/members/entity/Member.java
  src/main/java/com/spring/tming/domain/members/entity/MemberId.java
  src/main/java/com/spring/tming/domain/members/service/MemberService.java
Labels: feat

#121 지원한 모집글 전체조회
  src/main/java/com/spring/tming/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/spring/tming/domain/post/repository/custom/PostRepositoryImpl.java
  src/main/java/com/spring/tming/domain/post/service/PostService.java
Labels: feat, refactor

#127 신청승인된 모집글 전체조회
  src/main/java/com/spring/tming/domain/post/dto/response/PostMemberRes.java
  src/main/java/com/spring/tming/domain/post/dto/response/PostReadRes.java
  src/main/java/com/spring/tming/domain/post/entity/Post.java
  src/main/java/com/spring/tming/domain/post/repository/custom/PostRepositoryCustom.java
  src/main/java/com/spring/tming/domain/post/repository/custom/PostRepositoryImpl.java
  src/main/java/com/spring/tming/domain/post/service/PostService.java
  src/main/java/com/spring/tming/domain/post/service/PostServiceMapper.java
Labels: feat

#129 [FEAT] 팀원신청 승인 필요 클래스 작성 및 유효성 검사
  src/main/java/com/spring/tming/domain/applicant/validator/ApplicantValidator.java
  src/main/java/com/spring/tming/domain/chat/controller/RoomController.java
  src/main/java/com/spring/tming/domain/chat/service/RoomService.java
  src/main/java/com/spring/tming/domain/members/controller/MemberController.java
  src/main/java/com/spring/tming/domain/members/dto/request/MemberAdmitReq.java
  src/main/java/com/spring/tming/domain/members/dto/response/MemberAdmitRes.java
  src/main/java/com/spring/tming/domain/members/dto/response/MemberGetRes.java
  src/main/java/com/spring/tming/domain/members/dto/response/MemberGetResList.java
  src/main/java/com/spring/tming/domain/members/repository/MemberRepository.java
  src/main/java/com/spring/tming/domain/members/service/MemberService.java
  src/main/java/com/spring/tming/domain/members/service/MemberServiceMapper.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/validator/MemberValidator.java
Labels: feat, refactor

#137 Feature/add post read res l iked
  src/main/java/com/spring/tming/domain/post/dto/response/PostReadRes.java
  src/main/java/com/spring/tming/domain/post/entity/Post.java
  src/main/java/com/spring/tming/domain/post/service/PostService.java
  src/main/java/com/spring/tming/domain/post/service/PostServiceMapper.java
  src/test/java/com/spring/tming/domain/post/controller/PostControllerTest.java
Labels: refactor

#143 refactor: jwt 토큰 예외처리
  src/main/java/com/spring/tming/global/jwt/JwtUtil.java
  src/main/java/com/spring/tming/global/meta/ResultCode.java
  src/main/java/com/spring/tming/global/security/JwtAuthorizationFilter.java
  src/main/java/com/spring/tming/global/security/LogoutHandlerImpl.java
Labels: refactor
